---
target_policy_path: ../../policies

mappings:
  account_id:
    dev: "897722700244"
    stage: "897722700244"
    prod: "897722700244"

  team_code:
    orders: orders
    catalog: catalog
    checkout: checkout
    ui: ui
    cart: cart
    platform: pl

policy_generators:

  - name: orders_dynamodb_read
    template_path: ../../templates/{environment}/orders_dynamodb_read.json
    target_policy_path: ../../policies/generated/{environment}/{team}/{account}_Orders_Dynamodb_Read.json

    substitute:
      region: ap-south-1

      environment:
        - dev
        - stage
        - prod

      team:
        - orders

      account: mappings(account_id, environment)
      team_code: mappings(team_code, team)

  - name: catalog_dynamodb_read
    template_path: ../../templates/{environment}/catalog_dynamodb_read.json
    target_policy_path: ../../policies/generated/{environment}/{team}/{account}_Catalog_Dynamodb_Read.json

    substitute:
      region: ap-south-1

      environment:
        - dev
        - stage
        - prod

      team:
        - catalog

      account: mappings(account_id, environment)
      team_code: mappings(team_code, team)

  - name: karpenter_ec2_controller_policy
    template_path: ../../templates/{environment}/karpenter_ec2_controller_policy.json
    target_policy_path: ../../policies/generated/{environment}/{team}/{account}_karpenter_ec2_controller_policy.json

    substitute:
      region: ap-south-1

      environment:
        - dev

      team:
        - platform

      account: mappings(account_id, environment)
      team_code: mappings(team_code, team)

  - name: karpenter_iam_controller_policy
    template_path: ../../templates/{environment}/karpenter_iam_controller_policy.json
    target_policy_path: ../../policies/generated/{environment}/{team}/{account}_karpenter_iam_controller_policy.json

    substitute:
      region: ap-south-1

      environment:
        - dev

      team:
        - platform

      account: mappings(account_id, environment)
      team_code: mappings(team_code, team)
