---
name: Deploy Policy

on:
    workflow_dispatch:
        inputs:

            aws_region:
                description: 'AWS region to deploy to'
                required: true
                default: 'ap-south-1'

            aws_account_id:
                description: 'AWS account ID to deploy to'
                required: true
                default: '897722700244'

            working_directory:
                description: 'Working directory for the deployment'
                required: true
                default: 'src'

            python_module_path:
                description: 'Python module path for the deployment'
                required: true
                default: 'iam_policy_manager.main'

            environment:
                description: 'Environment to deploy to'
                required: true
                default: 'dev'
                type: choice
                options:
                    - dev
                    - staging
                    - prod

            config_file:
                description: 'Configuration file to deploy'
                required: true
                default: 'config.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show GitHub context
        run: |
           echo "Repository: $GITHUB_REPOSITORY"
           echo "Ref: $GITHUB_REF"
           echo "Event: $GITHUB_EVENT_NAME"
           echo "Workflow: $GITHUB_WORKFLOW"
           echo "Run ID: $GITHUB_RUN_ID"

      - name: Debug OIDC token
        run: |
          TOKEN=$(curl -sSL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value')
          echo "$TOKEN" | cut -d. -f2 | base64 -d 2>/dev/null | jq .
        env:
          ACTIONS_ID_TOKEN_REQUEST_URL: ${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }}
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
            role-to-assume: arn:aws:iam::${{ github.event.inputs.aws_account_id }}:role/gp-terraform-execution
            aws-region: ${{ github.event.inputs.aws_region }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Deploy policy
        run: |
          python -m ${{ github.event.inputs.python_module_path }}  ${{ github.event.inputs.config_file }}